### ISSUE TITLE
Ubuntu 14.04 Not Logging Passwords

### ISSUE THREAD

**Issue by noncetonic** [ColumPaget/pam_honeycreds#1]
Adding the following to /etc/pam.d/sshd : 

```
# Standard Un*x authorization.
@include common-account
auth required pam_honeycreds.so syslog logcreds denyall
```

When trying to authenticate I see the attempts in `/var/log/auth.log` but nothing is logged into `/var/log/syslog`

**Comment by ColumPaget** [comment]
One thing to check is that you've got "UsePAM yes" in your /etc/ssh/sshd_config and that sshd is compiled to use PAM. 

then there's the question of what's in your 'common-account' file. I think that if there's a line in there that says something is 'sufficient' then likely the auth process will return at that point.  Could you post your common-account file?

**Comment by ColumPaget** [comment]
Hi noncetonic,

did you get anywhere with this? can I close the issue?

Colum
